name: Automated tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - fist_test
          - second_test
          

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: first test
        if: "github.event.inputs.deployment_target == 'first_test'"
        run: pytest test_store.py::TestStore::test_store
      - name: second test
        if: "github.event.inputs.deployment_target == 'second_test'"
        run: pytest test_store.py::TestStore::test_store_2
